# Generated by Django 5.2.15 on 2026-07-04 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cantidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolios.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolios.portafolio')),
            ],
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('precio', models.DecimalField(decimal_places=6, max_digits=10)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolios.activo')),
            ],
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=6, max_digits=10)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolios.activo')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolios.portafolio')),
            ],
        ),
    ]
