# Generated by Django 5.2.15 on 2026-07-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portafolio',
            name='valor_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
