# Generated by Django 5.2.15 on 2026-07-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolios', '0002_alter_portafolio_valor_inicial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cantidad',
            constraint=models.UniqueConstraint(fields=('portafolio', 'activo'), name='unique_cantidad_portafolio_activo'),
        ),
        migrations.AddConstraint(
            model_name='precio',
            constraint=models.UniqueConstraint(fields=('activo', 'fecha'), name='unique_precio_activo_fecha'),
        ),
        migrations.AddConstraint(
            model_name='weight',
            constraint=models.UniqueConstraint(fields=('portafolio', 'activo'), name='unique_weight_portafolio_activo'),
        ),
    ]
